export type KnowledgeEntry = {
  id: string;
  surfaces: string[];
  keywords: string[];
  es: string;
  en: string;
};

export const KNOWLEDGE: KnowledgeEntry[] = [
  {id:"monthly-ai",surfaces:["powerfit360","web"],keywords:["mensualidad","pago","pagada","generaciones","creditos ia","créditos ia","cuantas generaciones","4 generaciones"],es:"Cada mensualidad registrada como pagada acredita 4 generaciones IA. Si una transacción cubre varios meses, se acreditan 4 por cada mes pagado. Cada planificación guardada correctamente consume 1 generación.",en:"Each posted monthly membership payment grants 4 AI generations. If one transaction covers several months, you receive 4 per paid month. Each successfully saved workout uses 1 generation."},
  {id:"generator",surfaces:["powerfit360"],keywords:["generador","generar plan","planificacion","planificación","rutina ia","entrenamiento ia"],es:"En Generador IA selecciona alumno, objetivo, modalidad, nivel, duración y contexto. PowerFit intenta usar IA y, si el proveedor no está disponible, activa el motor interno de contingencia para entregar igualmente una planificación válida.",en:"In AI Generator choose student, goal, modality, level, duration and context. PowerFit uses AI when available and falls back to its internal planning engine if the provider is unavailable."},
  {id:"generator-error",surfaces:["powerfit360"],keywords:["no genera","error generador","saldo openai","sin saldo","credit_balance_exhausted"],es:"Si el proveedor IA no tiene saldo o está temporalmente caído, PowerFit debe usar el motor interno de contingencia. El crédito del alumno solo se descuenta cuando una planificación válida se genera y guarda correctamente.",en:"If the AI provider is out of credit or temporarily unavailable, PowerFit uses the internal fallback engine. A student credit is only consumed when a valid plan is generated and saved."},
  {id:"extra-generations",surfaces:["powerfit360","web"],keywords:["comprar generaciones","generaciones extra","más generaciones","mas generaciones","creditos extra"],es:"Además de las 4 generaciones incluidas por mensualidad pagada, PowerFit puede ofrecer paquetes adicionales desde el Generador IA cuando estén activos para tu cuenta.",en:"In addition to the 4 generations included per paid membership month, PowerFit can offer extra generation packages from the AI Generator when enabled."},
  {id:"payment-status",surfaces:["powerfit360"],keywords:["estado pago","moroso","pagado","pendiente","vencimiento","fecha vencimiento"],es:"Revisa la sección Pago / deuda. Allí verás el estado actual, vencimiento y opciones disponibles. Un administrador puede registrar pagos manuales y Mercado Pago puede actualizar pagos confirmados.",en:"Check Payment / debt to see your current status, due date and available options. Admins can register manual payments and Mercado Pago can update confirmed payments."},
  {id:"mercadopago",surfaces:["powerfit360","web"],keywords:["mercado pago","mercadopago","pagar online","tarjeta","checkout"],es:"PowerFit usa Mercado Pago para pagos online cuando el checkout está habilitado. La confirmación final se valida en servidor antes de actualizar el estado del alumno.",en:"PowerFit uses Mercado Pago for online payments when checkout is enabled. Final payment confirmation is verified server-side before the student status is updated."},
  {id:"login",surfaces:["powerfit360","web"],keywords:["iniciar sesion","iniciar sesión","login","entrar","acceso"],es:"Usa el correo asociado a tu cuenta PowerFit360. Si no puedes entrar, revisa que el correo sea correcto y usa recuperación de contraseña desde la pantalla de acceso.",en:"Use the email linked to your PowerFit360 account. If you cannot sign in, verify the email and use password recovery from the login screen."},
  {id:"password",surfaces:["powerfit360","web"],keywords:["contraseña","password","olvide","olvidé","recuperar contraseña"],es:"Desde la pantalla de acceso solicita recuperación de contraseña. Abre el enlace recibido en tu correo y define una nueva clave.",en:"Use password recovery from the login screen. Open the email link and set a new password."},
  {id:"language",surfaces:["powerfit360","cps","web"],keywords:["idioma","ingles","inglés","english","español"],es:"PowerFit360 y CPS están preparados para español e inglés. Puedes cambiar el idioma desde la interfaz cuando la opción esté disponible.",en:"PowerFit360 and CPS support Spanish and English. You can switch language from the interface where available."},
  {id:"attendance",surfaces:["powerfit360"],keywords:["asistencia","qr","check in","check-in","marcar asistencia"],es:"La asistencia se registra mediante QR. Abre Asistencia QR o Mi QR según tu rol y sigue el flujo de check-in mostrado por la app.",en:"Attendance is registered by QR. Open QR Attendance or My QR depending on your role and follow the check-in flow shown in the app."},
  {id:"routines",surfaces:["powerfit360"],keywords:["rutinas","mis rutinas","entrenamientos","plan guardado","planes"],es:"Las planificaciones generadas o asignadas se consultan desde Rutinas. Allí puedes revisar sesiones guardadas y el trabajo indicado por tu entrenador.",en:"Generated or assigned plans are available under Routines. There you can review saved sessions and coach-assigned work."},
  {id:"builder",surfaces:["powerfit360"],keywords:["constructor","crear rutina manual","armar entrenamiento"],es:"Constructor permite crear sesiones manualmente sin usar una generación IA, combinando ejercicios y bloques según la edición habilitada.",en:"Workout Builder lets you create sessions manually without spending an AI generation, combining exercises and blocks according to your enabled edition."},
  {id:"library",surfaces:["powerfit360"],keywords:["biblioteca","metodos","métodos","ejercicios","contenido"],es:"La Biblioteca/Métodos reúne contenido técnico y recursos de entrenamiento disponibles según tu edición y permisos.",en:"Library/Methods contains technical content and training resources available according to your edition and permissions."},
  {id:"profile",surfaces:["powerfit360"],keywords:["perfil","ficha","datos personales","telefono","teléfono","emergencia"],es:"En Ficha personal puedes consultar tus datos de perfil. Los cambios disponibles dependen de tu rol y de la configuración del gimnasio.",en:"Personal Profile shows your account details. Available edits depend on your role and gym configuration."},
  {id:"notifications",surfaces:["powerfit360"],keywords:["notificaciones","avisos","mensaje del gym","alertas"],es:"La sección Notificaciones muestra avisos del sistema o del gimnasio cuando están habilitados.",en:"Notifications shows system or gym notices when enabled."},
  {id:"xp",surfaces:["powerfit360"],keywords:["xp","rango","rangos","puntos"],es:"XP y Rangos muestra tu progreso gamificado cuando esa función está habilitada para tu edición.",en:"XP & Ranks shows gamified progress when that feature is enabled for your edition."},
  {id:"admin",surfaces:["powerfit360"],keywords:["administrador","admin alumnos","gestionar alumno","editar alumno"],es:"Los administradores pueden gestionar alumnos, pagos, registros, graduaciones, reportes y otras funciones según permisos. Los alumnos no tienen acceso a esas herramientas.",en:"Admins can manage students, payments, records, graduations, reports and other permitted tools. Students do not have access to admin functions."},
  {id:"coach",surfaces:["powerfit360","cps"],keywords:["coach","profesor","entrenador","evaluar"],es:"El rol coach/profesor puede revisar trabajo de alumnos y evaluaciones cuando tiene asignación y permisos correspondientes.",en:"Coach/teacher roles can review student work and evaluations when properly assigned and authorized."},
  {id:"cps-what",surfaces:["cps","powerfit360","web"],keywords:["que es cps","qué es cps","combat performance","cps fighter","cps coach"],es:"CPS significa Combat Performance System. Es un sistema progresivo para aprender y enseñar deportes de combate, con rutas Fighter y Coach y foco en Boxeo, Kickboxing y K1.",en:"CPS means Combat Performance System. It is a progressive system for learning and teaching combat sports, with Fighter and Coach paths focused on Boxing, Kickboxing and K1."},
  {id:"cps-tomos",surfaces:["cps","powerfit360","web"],keywords:["cuantos tomos","cuántos tomos","15 tomos","tomos cps"],es:"CPS tiene 15 tomos. Los tomos organizan contenidos técnicos, evaluaciones y progresión dentro del sistema.",en:"CPS has 15 tomos. They organize technical content, assessments and progression through the system."},
  {id:"boxing-route",surfaces:["cps","powerfit360"],keywords:["boxeo nivel","niveles boxeo","cinturon boxeo","cinturón boxeo"],es:"En Boxeo no se usan cinturones por color dentro de CPS. La progresión se expresa como Boxeo Nivel 1, Nivel 2 y así sucesivamente.",en:"Boxing does not use colored belts in CPS. Progression is expressed as Boxing Level 1, Level 2 and so on."},
  {id:"kick-route",surfaces:["cps","powerfit360"],keywords:["kickboxing cinturones","grados kickboxing","blanco","naranjo","verde","azul","cafe","café","negro"],es:"Kickboxing usa una progresión por grados/cinturones. Cada avance requiere completar el contenido y las evaluaciones correspondientes.",en:"Kickboxing uses a grade/belt progression. Each promotion requires completing the relevant content and assessments."},
  {id:"tomo-price",surfaces:["cps","powerfit360","web"],keywords:["precio tomo","5000","cinco mil","pagar tomo"],es:"Para miembros de la Escuela, el valor configurado por tomo CPS es de $5.000 CLP, sujeto a las reglas comerciales vigentes de la escuela.",en:"For school members, the configured CPS tomo price is CLP $5,000, subject to the school's current commercial rules."},
  {id:"unlock-tomo",surfaces:["cps","powerfit360"],keywords:["abrir tomo","desbloquear tomo","tomo bloqueado","acceso tomo"],es:"Un tomo se habilita según el acceso registrado para el alumno. Puede depender de pago, concesión administrativa, progreso o reglas de la ruta.",en:"A tomo becomes available according to the student's recorded entitlement. Access can depend on payment, admin grant, progression or route rules."},
  {id:"download-tomo",surfaces:["cps","powerfit360"],keywords:["descargar tomo","download tomo","pdf tomo","no descarga"],es:"Cuando tu acceso al tomo lo permite, usa Descargar tomo. La descarga se genera desde el navegador y no depende de un endpoint externo antiguo.",en:"When your tomo access allows it, use Download tomo. The download is generated in the browser and no longer relies on the old external endpoint."},
  {id:"video-upload",surfaces:["cps","powerfit360"],keywords:["subir video","video tecnica","video técnica","enviar video","donde subo"],es:"Abre tu tomo y entra a la tarjeta técnica correspondiente. Cuando la tarjeta exige demostración, allí aparece la opción para subir el video.",en:"Open your tomo and select the relevant technique card. When a demonstration is required, the video upload option appears there."},
  {id:"video-formats",surfaces:["cps","powerfit360"],keywords:["formato video","mp4","webm","mov","peso video","100 mb"],es:"Los videos CPS aceptados están limitados a formatos permitidos como MP4/WebM/MOV y al tamaño máximo configurado. Si el archivo supera el límite, comprímelo antes de subirlo.",en:"CPS videos are limited to allowed formats such as MP4/WebM/MOV and the configured maximum size. Compress files that exceed the limit before uploading."},
  {id:"video-review",surfaces:["cps","powerfit360"],keywords:["evaluacion video","evaluación video","puntaje video","aprobar video","correccion video","corrección video"],es:"El coach revisa guardia, base, mecánica, cadena cinética, coordinación, recuperación, control y ejecución completa. Puede aprobar o solicitar corrección.",en:"The coach reviews guard, stance, mechanics, kinetic chain, coordination, recovery, control and complete execution. They can approve or request corrections."},
  {id:"live-review",surfaces:["cps","powerfit360"],keywords:["evaluacion presencial","evaluación presencial","en vivo","live assessment","prueba presencial"],es:"Después de cumplir los requisitos técnicos, el alumno puede pasar a evaluación presencial. El coach registra el puntaje y decisión en el sistema.",en:"After meeting the technical requirements, the student can proceed to an in-person assessment. The coach records the score and decision in the system."},
  {id:"tomo-test",surfaces:["cps","powerfit360"],keywords:["prueba tomo","examen tomo","tomo test","pasar tomo"],es:"Al completar tarjetas, videos y requisitos de evaluación, el tomo puede quedar elegible para prueba. Aprobar esa prueba permite continuar la progresión definida.",en:"After completing cards, videos and assessment requirements, the tomo can become test-eligible. Passing the test allows progression to continue."},
  {id:"graduation",surfaces:["cps","powerfit360"],keywords:["graduacion","graduación","subir nivel","subir grado","promocion","promoción"],es:"La graduación no depende de una sola nota: considera tomos, tarjetas técnicas, videos, evaluación presencial, pruebas y aprobación correspondiente según la ruta.",en:"Graduation is not based on one score alone. It considers tomos, technique cards, video reviews, live assessment, tests and the required approval for the route."},
  {id:"cps-progress",surfaces:["cps","powerfit360"],keywords:["mi progreso","avance cps","que me falta","qué me falta","siguiente tomo"],es:"Revisa Mi Camino/CPS para ver tu ruta, tomo actual y estados de progreso. Los pasos pendientes dependen de tarjetas, videos, evaluaciones y pruebas.",en:"Check My Path/CPS to see your route, current tomo and progression states. Pending steps depend on cards, videos, assessments and tests."},
  {id:"cps-disciplines",surfaces:["cps","web"],keywords:["boxeo kickboxing k1","disciplinas","deportes cps"],es:"CPS está diseñado para Boxeo, Kickboxing y K1, con contenidos compartidos y específicos según disciplina.",en:"CPS is designed for Boxing, Kickboxing and K1, with shared and discipline-specific content."},
  {id:"security",surfaces:["powerfit360","cps","web"],keywords:["seguridad","hack","datos seguros","api key","privacidad"],es:"PowerFit/CPS usan RLS, storage privado, rate limiting, funciones server-side, escaneo de secretos, CSP y auditorías de dependencias. Las claves privadas no se exponen en el navegador.",en:"PowerFit/CPS use RLS, private storage, rate limiting, server-side functions, secret scanning, CSP and dependency audits. Private keys are not exposed in the browser."},
  {id:"privacy",surfaces:["powerfit360","cps","web"],keywords:["privacidad","mis datos","datos personales","quien ve"],es:"Los datos se muestran según rol y permisos. Un alumno no debe poder consultar información privada de otro alumno; las acciones sensibles se validan en servidor.",en:"Data is exposed according to roles and permissions. Students should not be able to access another student's private data; sensitive actions are validated server-side."},
  {id:"chatgpt",surfaces:["powerfit360","cps","web"],keywords:["chatgpt","dastan","hablar con dastan","hablar con chatgpt"],es:"Para una conversación más profunda puedes usar el botón Hablar con Dastan en ChatGPT. El asistente interno resuelve dudas frecuentes sin consumir API y ChatGPT se usa para consultas complejas cuando tú lo decidas.",en:"For deeper conversations use Talk to Dastan in ChatGPT. The internal assistant handles frequent questions without API cost, while ChatGPT is used for complex questions when you choose."},
  {id:"support",surfaces:["powerfit360","cps","web"],keywords:["ayuda","soporte","no funciona","problema app","error app"],es:"Indica qué pantalla estás usando, qué botón presionaste y el mensaje de error exacto. Si puedes, agrega una captura. Eso permite identificar el problema sin modificar datos innecesariamente.",en:"Tell me which screen you are using, what button you pressed and the exact error message. A screenshot helps diagnose the issue without unnecessary data changes."},
];

function normalize(text: string) {
  return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

export function findKnowledgeAnswer(message: string, surface: string, locale: "es" | "en" = "es") {
  const haystack = normalize(message);
  let best: KnowledgeEntry | null = null;
  let bestScore = 0;

  for (const entry of KNOWLEDGE) {
    if (!entry.surfaces.includes(surface) && !entry.surfaces.includes("web")) continue;
    let score = 0;
    for (const keyword of entry.keywords) {
      const k = normalize(keyword);
      if (haystack.includes(k)) score += Math.max(1, k.split(/\s+/).length * 2);
    }
    if (score > bestScore) {
      best = entry;
      bestScore = score;
    }
  }

  return bestScore > 0 && best ? { id: best.id, reply: locale === "en" ? best.en : best.es, score: bestScore } : null;
}

export const SUGGESTIONS = {
  powerfit360: {
    es: ["¿Cuántas generaciones IA tengo?", "¿Cómo genero una planificación?", "¿Cómo pago mi mensualidad?", "¿Dónde veo mis rutinas?", "¿Cómo funciona la asistencia QR?", "¿Qué es CPS?"],
    en: ["How many AI generations do I have?", "How do I generate a workout?", "How do I pay my membership?", "Where are my routines?", "How does QR attendance work?", "What is CPS?"],
  },
  cps: {
    es: ["¿Qué tomo me corresponde?", "¿Dónde subo mi video?", "¿Cómo me evalúan?", "¿Cómo descargo un tomo?", "¿Cómo avanzo de nivel o grado?", "¿Cuántos tomos tiene CPS?"],
    en: ["Which tomo is mine?", "Where do I upload my video?", "How am I assessed?", "How do I download a tomo?", "How do I advance?", "How many tomos are in CPS?"],
  },
  web: {
    es: ["¿Qué es PowerFit360?", "¿Qué es CPS?", "¿Cuánto vale un tomo?", "¿Cómo funcionan las mensualidades?", "¿Qué incluye el Generador IA?", "¿Cómo empiezo?"],
    en: ["What is PowerFit360?", "What is CPS?", "How much is a tomo?", "How do memberships work?", "What does AI Generator include?", "How do I start?"],
  },
};
